Resources:
  PagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.pagesTableName}
      AttributeDefinitions:
        - AttributeName: uri
          AttributeType: S
        # - AttributeName: date_created
        #   AttributeType: S
      KeySchema:
        - AttributeName: uri
          KeyType: HASH
        # - AttributeName: date_created
        #   KeyType: RANGE
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  CategoriesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.categoriesTableName}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        # - AttributeName: date_created
        #   AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        # - AttributeName: date_created
        #   KeyType: RANGE
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.usersTableName}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        # - AttributeName: date_created
        #   AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        # - AttributeName: date_created
        #   KeyType: RANGE
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  SiteTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.siteTableName}
      AttributeDefinitions:
        - AttributeName: domain
          AttributeType: S
        # - AttributeName: date_created
        #   AttributeType: S
      KeySchema:
        - AttributeName: domain
          KeyType: HASH
        # - AttributeName: date_created
        #   KeyType: RANGE
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1